/**
	Scripted by Migrate2Postgres 1.0.7 on Tue, 9 Oct 2018 03:30:23 +0300

	Migrate2Postgres Copyright (C) 2018 Igal Sapir
	This program comes with ABSOLUTELY NO WARRANTY;
	This is free software, and you are welcome to redistribute it
	under certain conditions;
	See https://www.gnu.org/licenses/gpl-3.0.txt for details
	
	Available at https://github.com/isapir/Migrate2Postgres
**/

BEGIN TRANSACTION;

CREATE SCHEMA IF NOT EXISTS public;


DROP TABLE IF EXISTS public.AccessRight;
CREATE TABLE public.AccessRight (
	 Id                  	INT         	NOT NULL
	,Title               	TEXT        	NOT NULL
	,ConstName           	TEXT        	NOT NULL
	,GroupTitle          	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.Account;
CREATE TABLE public.Account (
	 Account_ID          	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Account_Login       	TEXT        	NOT NULL
	,Account_DisplayName 	TEXT        	NOT NULL
	,Account_Disabled    	BOOLEAN     	NOT NULL
	,Account_Description 	TEXT        	NOT NULL
	,Account_PasswordSetDate	TIMESTAMPTZ 	NOT NULL
	,Account_DisabledDate	TIMESTAMPTZ
	,Account_ExpirationDate	TIMESTAMPTZ
	,Account_SessionTimeout	INT         	NOT NULL
	,Account_SessionCount	INT         	NOT NULL
	,Account_IpAddressMode	BOOLEAN     	NOT NULL
	,Account_LastLoginDate	TIMESTAMPTZ
	,Account_IsSystem    	BOOLEAN     	NOT NULL
	,MobilePhone         	TEXT        	NOT NULL
	,EMail               	TEXT        	NOT NULL
	,SmsEMail            	TEXT        	NOT NULL
	,SendSmsViaModem     	BOOLEAN     	NOT NULL
	,NotifyStartTime     	INT         	NOT NULL
	,NotifyEndTime       	INT         	NOT NULL
	,Password            	BYTEA       	NOT NULL
	,Salt                	BYTEA       	NOT NULL
	,HasAllNodeAccess    	BOOLEAN     	NOT NULL
	,StartPage           	INT         	NOT NULL
	,TenantOfficeOnly    	BOOLEAN     	NOT NULL
	,AllowAllReports     	BOOLEAN     	NOT NULL
	,DisablePasswordChange	BOOLEAN     	NOT NULL
	,PasswordResetToken  	TEXT        	NOT NULL
	,PasswordResetTokenExpireDateTime	TIMESTAMPTZ
	,AllowAllMaps        	BOOLEAN     	NOT NULL
	,ReportCenterFormMode	INT         	NOT NULL  DEFAULT 0
	,UseSendIntervalForEmail	BOOLEAN     	NOT NULL
	,AuthenticationModes 	INT         	NOT NULL
	,WindowsSid          	TEXT
	,DivisionId          	INT
	,LoginNotAllowed     	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.AccountGroup;
CREATE TABLE public.AccountGroup (
	 ID                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Title               	TEXT        	NOT NULL
	,IsSystem            	BOOLEAN     	NOT NULL
	,DivisionId          	INT
);

DROP TABLE IF EXISTS public.AccountGroupMembership;
CREATE TABLE public.AccountGroupMembership (
	 AccountID           	INT         	NOT NULL
	,AccountGroupID      	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.AccountGroupPermissionEx;
CREATE TABLE public.AccountGroupPermissionEx (
	 AccountGroupId      	INT         	NOT NULL
	,AccessRightId       	INT         	NOT NULL
	,IsDenied            	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.AccountLog;
CREATE TABLE public.AccountLog (
	 Date                	TIMESTAMPTZ 	NOT NULL
	,AccountId           	INT         	NOT NULL
	,Importance          	INT         	NOT NULL
	,Message             	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.AccountMap;
CREATE TABLE public.AccountMap (
	 AccountId           	INT         	NOT NULL
	,MapId               	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.AccountMeasurePoint;
CREATE TABLE public.AccountMeasurePoint (
	 AccountId           	INT         	NOT NULL
	,MeasurePointId      	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.AccountNode;
CREATE TABLE public.AccountNode (
	 AccountId           	INT         	NOT NULL
	,NodeId              	INT         	NOT NULL
	,MeasurePointCheckAccessMode	INT         	NOT NULL
	,AllowedSystemTypes  	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.AccountNodeGroup;
CREATE TABLE public.AccountNodeGroup (
	 AccountId           	INT         	NOT NULL
	,NodeGroupId         	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.AccountNotification;
CREATE TABLE public.AccountNotification (
	 AccountId           	INT         	NOT NULL
	,NotificationId      	INT         	NOT NULL
	,IsRead              	BOOLEAN     	NOT NULL  DEFAULT false
);

DROP TABLE IF EXISTS public.AccountNotificationIncident;
CREATE TABLE public.AccountNotificationIncident (
	 AccountId           	INT         	NOT NULL
	,IncidentTypeId      	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.AccountNotificationMethod;
CREATE TABLE public.AccountNotificationMethod (
	 AccountId           	INT         	NOT NULL
	,NotificationTypeId  	INT         	NOT NULL
	,NotificationMethodMask	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.AccountNotificationNode;
CREATE TABLE public.AccountNotificationNode (
	 AccountId           	INT         	NOT NULL
	,NotificationTypeId  	INT         	NOT NULL
	,NodeId              	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.AccountNotificationNodeJobType;
CREATE TABLE public.AccountNotificationNodeJobType (
	 AccountId           	INT         	NOT NULL
	,NodeJobType         	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.AccountPermissionEx;
CREATE TABLE public.AccountPermissionEx (
	 AccountId           	INT         	NOT NULL
	,AccessRightId       	INT         	NOT NULL
	,IsDenied            	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.AccountPersonalAccount;
CREATE TABLE public.AccountPersonalAccount (
	 AccountId           	INT         	NOT NULL
	,PersonalAccountId   	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.AccountReport;
CREATE TABLE public.AccountReport (
	 AccountId           	INT         	NOT NULL
	,ReportId            	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.AccountServiceCompany;
CREATE TABLE public.AccountServiceCompany (
	 AccountId           	INT         	NOT NULL
	,ServiceCompanyId    	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.Adapter;
CREATE TABLE public.Adapter (
	 ID                  	INT         	NOT NULL
	,Title               	TEXT        	NOT NULL
	,Comment             	TEXT        	NOT NULL
	,IsAddressRequired   	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.BalanceGroup;
CREATE TABLE public.BalanceGroup (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Title               	TEXT
);

DROP TABLE IF EXISTS public.BalanceGroupMeasurePoint;
CREATE TABLE public.BalanceGroupMeasurePoint (
	 BalanceGroupId      	INT         	NOT NULL
	,MeasurePointId      	INT         	NOT NULL
	,IsHead              	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.Cell;
CREATE TABLE public.Cell (
	 ID                  	INT         	NOT NULL
	,Name                	TEXT        	NOT NULL
	,DriverCode          	TEXT        	NOT NULL
	,DeviceDataType      	INT         	NOT NULL
	,EquipmentModelId    	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.Complex;
CREATE TABLE public.Complex (
	 Complex_ResponseDelay	INT         	NOT NULL  DEFAULT 0
	,Complex_PollSessionID	INT
	,ProtocolTypeID      	INT
	,Tag                 	BYTEA
	,AdapterID           	INT
	,AdapterAddress      	INT         	NOT NULL  DEFAULT 0
	,HardwareVersion     	TEXT
	,FirmwareVersion     	TEXT
	,TimeDifference      	INT
	,BatteryLevel        	REAL
	,EquipmentId         	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.Contingency;
CREATE TABLE public.Contingency (
	 ID                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,MeasurePointID      	INT
	,NodeID              	INT         	NOT NULL
	,ContingencyTypeID   	INT         	NOT NULL
	,StartDate           	TIMESTAMPTZ 	NOT NULL
	,EndDate             	TIMESTAMPTZ 	NOT NULL
	,DiagDate            	TIMESTAMPTZ 	NOT NULL
	,Importance          	INT         	NOT NULL
	,IsClosed            	BOOLEAN     	NOT NULL
	,Description         	TEXT
	,SmsMessage          	TEXT
	,EquipmentId         	INT
	,DataType            	INT         	NOT NULL
	,Distinction         	BYTEA
);

DROP TABLE IF EXISTS public.ContingencyLog;
CREATE TABLE public.ContingencyLog (
	 ContingencyID       	INT         	NOT NULL
	,Date                	TIMESTAMPTZ 	NOT NULL
	,Message             	TEXT
	,ShortMessage        	TEXT
);

DROP TABLE IF EXISTS public.ContractConsumption;
CREATE TABLE public.ContractConsumption (
	 MeasuredParameterId 	INT         	NOT NULL
	,Year                	INT         	NOT NULL
	,Jan                 	REAL          DEFAULT 0
	,Feb                 	REAL          DEFAULT 0
	,Mar                 	REAL          DEFAULT 0
	,Apr                 	REAL          DEFAULT 0
	,May                 	REAL          DEFAULT 0
	,Jun                 	REAL          DEFAULT 0
	,Jul                 	REAL          DEFAULT 0
	,Aug                 	REAL          DEFAULT 0
	,Sep                 	REAL          DEFAULT 0
	,Oct                 	REAL          DEFAULT 0
	,Nov                 	REAL          DEFAULT 0
	,Dec                 	REAL          DEFAULT 0
	,MeasurePointId      	INT         	NOT NULL
	,ContractConsumptionType	INT         	NOT NULL  DEFAULT 0
);

DROP TABLE IF EXISTS public.ContractConsumptionLimit;
CREATE TABLE public.ContractConsumptionLimit (
	 MeasurePointId      	INT         	NOT NULL
	,MeasuredParameterId 	INT         	NOT NULL
	,Year                	INT         	NOT NULL
	,Jan                 	REAL          DEFAULT 0
	,Feb                 	REAL          DEFAULT 0
	,Mar                 	REAL          DEFAULT 0
	,Apr                 	REAL          DEFAULT 0
	,May                 	REAL          DEFAULT 0
	,Jun                 	REAL          DEFAULT 0
	,Jul                 	REAL          DEFAULT 0
	,Aug                 	REAL          DEFAULT 0
	,Sep                 	REAL          DEFAULT 0
	,Oct                 	REAL          DEFAULT 0
	,Nov                 	REAL          DEFAULT 0
	,Dec                 	REAL          DEFAULT 0
	,ContractConsumptionType	INT         	NOT NULL  DEFAULT 0
);

DROP TABLE IF EXISTS public.ContractTemperature;
CREATE TABLE public.ContractTemperature (
	 NodeId              	INT         	NOT NULL
	,T_outdoor           	INT         	NOT NULL
	,T_in                	REAL        	NOT NULL
	,T_out               	REAL        	NOT NULL
);

DROP TABLE IF EXISTS public.CounterTotals;
CREATE TABLE public.CounterTotals (
	 EquipmentId         	INT         	NOT NULL
	,DataDate            	TIMESTAMPTZ 	NOT NULL
	,Value1              	REAL        	NOT NULL
	,Value2              	REAL        	NOT NULL
	,IsTrustedValue      	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.CustomAttribute;
CREATE TABLE public.CustomAttribute (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Title               	TEXT        	NOT NULL
	,Code                	TEXT        	NOT NULL
	,Comment             	TEXT        	NOT NULL
	,Entities            	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.Customer;
CREATE TABLE public.Customer (
	 ID                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Title               	TEXT        	NOT NULL
	,IsNaturalPerson     	BOOLEAN     	NOT NULL
	,VatId               	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.DataInterface;
CREATE TABLE public.DataInterface (
	 EquipmentModelId    	INT         	NOT NULL
	,PortSettings        	TEXT        	NOT NULL
	,SupportedPortSpeeds 	INT         	NOT NULL
	,SupportedFlowControls	INT         	NOT NULL
	,DefaultPassword     	TEXT        	NOT NULL
	,PasswordRegEx       	TEXT        	NOT NULL
	,PasswordComment     	TEXT        	NOT NULL
	,MaxNetworkSize      	INT         	NOT NULL
	,NetworkAddressDefault	TEXT        	NOT NULL
	,NetworkAddressUsage 	INT         	NOT NULL
	,NetworkAddressComment	TEXT        	NOT NULL
	,NetworkAddressRegEx 	TEXT        	NOT NULL
	,NetworkAddressRangeMin	INT         	NOT NULL
	,NetworkAddressRangeMax	INT         	NOT NULL
	,Features            	INT         	NOT NULL
	,SecondLevelPasswordComment	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.DataParameter;
CREATE TABLE public.DataParameter (
	 ID                  	INT         	NOT NULL
	,Code                	TEXT        	NOT NULL
	,Title               	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.DataStatus;
CREATE TABLE public.DataStatus (
	 MeasurePointID      	INT         	NOT NULL
	,DeviceDataType      	INT         	NOT NULL
	,StartDate           	TIMESTAMPTZ 	NOT NULL
	,EndDate             	TIMESTAMPTZ 	NOT NULL
	,DataStatus          	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.DeviceAddress;
CREATE TABLE public.DeviceAddress (
	 Address             	INT         	NOT NULL
	,MeasurePointID      	INT         	NOT NULL
	,DataParameterID     	INT         	NOT NULL
	,DeviceDataType      	INT         	NOT NULL
	,UnitID              	INT         	NOT NULL
	,ArchiveDepth        	INT         	NOT NULL
	,EquipmentId         	INT         	NOT NULL
	,Multiplier          	REAL        	NOT NULL
);

DROP TABLE IF EXISTS public.DeviceCell;
CREATE TABLE public.DeviceCell (
	 CellID              	INT         	NOT NULL
	,MeasurePointID      	INT         	NOT NULL
	,DataParameterID     	INT         	NOT NULL
	,PulseRatio          	REAL        	NOT NULL
	,UnitID              	INT
	,DataType            	INT         	NOT NULL
	,EquipmentId         	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.DeviceChannel;
CREATE TABLE public.DeviceChannel (
	 HeatLeadIn          	INT         	NOT NULL
	,ChannelNumber       	INT         	NOT NULL
	,MeasurePointID      	INT         	NOT NULL
	,IsSupplyChannel     	BOOLEAN     	NOT NULL
	,EquipmentId         	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.DeviceConfig;
CREATE TABLE public.DeviceConfig (
	 DateTime            	TIMESTAMPTZ 	NOT NULL
	,ParamId             	INT         	NOT NULL
	,ParamValue          	TEXT        	NOT NULL
	,EquipmentId         	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.DeviceConfigParam;
CREATE TABLE public.DeviceConfigParam (
	 Id                  	INT         	NOT NULL
	,Title               	TEXT        	NOT NULL
	,DataType            	VARCHAR(1)  	NOT NULL
	,GeneralDeviceConfigParamId	INT
	,Comment             	TEXT        	NOT NULL
	,HeatLeadInNum       	INT
	,ChannelNum          	INT
	,ReadAddress         	INT
	,ReadDataType        	INT
	,DriverCode          	TEXT
	,EquipmentModelId    	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.DeviceDataType;
CREATE TABLE public.DeviceDataType (
	 ID                  	INT         	NOT NULL
	,"desc"              	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.DeviceEvent;
CREATE TABLE public.DeviceEvent (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,StartDateTime       	TIMESTAMPTZ
	,EventCode           	INT         	NOT NULL
	,Description         	TEXT        	NOT NULL
	,HeatLeadIn          	INT         	NOT NULL
	,ArchiveType         	INT         	NOT NULL
	,ChannelNumber       	INT         	NOT NULL
	,EndDateTime         	TIMESTAMPTZ
	,EquipmentId         	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.DeviceMeasurePoint;
CREATE TABLE public.DeviceMeasurePoint (
	 MeasurePointID      	INT         	NOT NULL
	,EquipmentId         	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.Division;
CREATE TABLE public.Division (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Title               	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.DriverInterface;
CREATE TABLE public.DriverInterface (
	 EquipmentModelId    	INT         	NOT NULL
	,DriverName          	TEXT        	NOT NULL
	,DriverStatus        	INT         	NOT NULL
	,ChannelCount        	INT         	NOT NULL
	,HeatSystemCount     	INT         	NOT NULL
	,MinMemoryAddress    	INT         	NOT NULL
	,MaxMemoryAddress    	INT         	NOT NULL
	,Features            	INT         	NOT NULL
	,SupportedDataTypes  	INT         	NOT NULL
	,TotalsResetThresholdM	REAL        	NOT NULL
	,TotalsResetThresholdQ	REAL        	NOT NULL
);

DROP TABLE IF EXISTS public.DryContactState;
CREATE TABLE public.DryContactState (
	 DateTime            	TIMESTAMPTZ 	NOT NULL
	,Value               	INT         	NOT NULL
	,EquipmentId         	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.EavConsumptionCurrents;
CREATE TABLE public.EavConsumptionCurrents (
	 MeasurePointId      	INT         	NOT NULL
	,DateTime            	TIMESTAMPTZ 	NOT NULL
	,DataParameterId     	INT         	NOT NULL
	,Value               	REAL        	NOT NULL
	,IsBad               	BOOLEAN     	NOT NULL
	,IsCalc              	BOOLEAN     	NOT NULL
	,IsInterpolated      	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.EavConsumptionDay;
CREATE TABLE public.EavConsumptionDay (
	 MeasurePointId      	INT         	NOT NULL
	,DateTime            	TIMESTAMPTZ 	NOT NULL
	,DataParameterId     	INT         	NOT NULL
	,Value               	REAL        	NOT NULL
	,IsBad               	BOOLEAN     	NOT NULL
	,IsCalc              	BOOLEAN     	NOT NULL
	,IsInterpolated      	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.EavConsumptionHour;
CREATE TABLE public.EavConsumptionHour (
	 MeasurePointId      	INT         	NOT NULL
	,DateTime            	TIMESTAMPTZ 	NOT NULL
	,DataParameterId     	INT         	NOT NULL
	,Value               	REAL        	NOT NULL
	,IsBad               	BOOLEAN     	NOT NULL
	,IsCalc              	BOOLEAN     	NOT NULL
	,IsInterpolated      	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.EavConsumptionLast;
CREATE TABLE public.EavConsumptionLast (
	 MeasurePointId      	INT         	NOT NULL
	,DateTime            	TIMESTAMPTZ 	NOT NULL
	,DataType            	INT         	NOT NULL
	,Attributes          	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.EavConsumptionLastValue;
CREATE TABLE public.EavConsumptionLastValue (
	 MeasurePointId      	INT         	NOT NULL
	,DataParameterId     	INT         	NOT NULL
	,Value               	REAL        	NOT NULL
	,IsBad               	BOOLEAN     	NOT NULL
	,IsCalc              	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.EavConsumptionMonth;
CREATE TABLE public.EavConsumptionMonth (
	 MeasurePointId      	INT         	NOT NULL
	,DateTime            	TIMESTAMPTZ 	NOT NULL
	,DataParameterId     	INT         	NOT NULL
	,Value               	REAL        	NOT NULL
	,IsBad               	BOOLEAN     	NOT NULL
	,IsCalc              	BOOLEAN     	NOT NULL
	,IsInterpolated      	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.EavTotalsLast;
CREATE TABLE public.EavTotalsLast (
	 MeasurePointId      	INT         	NOT NULL
	,DateTime            	TIMESTAMPTZ 	NOT NULL
	,Attributes          	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.EavTotalsLastValue;
CREATE TABLE public.EavTotalsLastValue (
	 MeasurePointId      	INT         	NOT NULL
	,DataParameterId     	INT         	NOT NULL
	,Value               	REAL        	NOT NULL
	,IsBad               	BOOLEAN     	NOT NULL
	,IsCalc              	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.ElectricConsumptionDay;
CREATE TABLE public.ElectricConsumptionDay (
	 MeasurePointID      	INT         	NOT NULL
	,DataDate            	TIMESTAMPTZ 	NOT NULL
	,Ap1                 	REAL
	,An1                 	REAL
	,Rp1                 	REAL
	,Rn1                 	REAL
	,Ap2                 	REAL
	,An2                 	REAL
	,Rp2                 	REAL
	,Rn2                 	REAL
	,Ap3                 	REAL
	,An3                 	REAL
	,Rp3                 	REAL
	,Rn3                 	REAL
	,Ap4                 	REAL
	,An4                 	REAL
	,Rp4                 	REAL
	,Rn4                 	REAL
	,Attributes          	INT
	,CalculatedValues    	INT
	,BadValues           	INT
	,Ap                  	REAL
	,An                  	REAL
	,Rp                  	REAL
	,Rn                  	REAL
	,InterpolatedValues  	INT
	,NormalOperationDuration	REAL
);

DROP TABLE IF EXISTS public.ElectricConsumptionHour;
CREATE TABLE public.ElectricConsumptionHour (
	 MeasurePointID      	INT         	NOT NULL
	,DataDate            	TIMESTAMPTZ 	NOT NULL
	,Ap1                 	REAL
	,An1                 	REAL
	,Rp1                 	REAL
	,Rn1                 	REAL
	,Ap2                 	REAL
	,An2                 	REAL
	,Rp2                 	REAL
	,Rn2                 	REAL
	,Ap3                 	REAL
	,An3                 	REAL
	,Rp3                 	REAL
	,Rn3                 	REAL
	,Ap4                 	REAL
	,An4                 	REAL
	,Rp4                 	REAL
	,Rn4                 	REAL
	,Attributes          	INT
	,CalculatedValues    	INT
	,BadValues           	INT
	,Ap                  	REAL
	,An                  	REAL
	,Rp                  	REAL
	,Rn                  	REAL
	,InterpolatedValues  	INT
	,NormalOperationDuration	REAL
);

DROP TABLE IF EXISTS public.ElectricConsumptionMonth;
CREATE TABLE public.ElectricConsumptionMonth (
	 MeasurePointID      	INT         	NOT NULL
	,DataDate            	TIMESTAMPTZ 	NOT NULL
	,Ap1                 	REAL
	,An1                 	REAL
	,Rp1                 	REAL
	,Rn1                 	REAL
	,Ap2                 	REAL
	,An2                 	REAL
	,Rp2                 	REAL
	,Rn2                 	REAL
	,Ap3                 	REAL
	,An3                 	REAL
	,Rp3                 	REAL
	,Rn3                 	REAL
	,Ap4                 	REAL
	,An4                 	REAL
	,Rp4                 	REAL
	,Rn4                 	REAL
	,Attributes          	INT
	,CalculatedValues    	INT
	,BadValues           	INT
	,Ap                  	REAL
	,An                  	REAL
	,Rp                  	REAL
	,Rn                  	REAL
	,InterpolatedValues  	INT
	,NormalOperationDuration	REAL
);

DROP TABLE IF EXISTS public.ElectricPower;
CREATE TABLE public.ElectricPower (
	 MeasurePointId      	INT         	NOT NULL
	,DataDate            	TIMESTAMPTZ 	NOT NULL
	,Flags               	INT         	NOT NULL
	,Interval            	INT         	NOT NULL
	,Pp                  	REAL
	,Pn                  	REAL
	,Qp                  	REAL
	,Qn                  	REAL
	,BadValues           	INT
);

DROP TABLE IF EXISTS public.ElectricPowerQuality;
CREATE TABLE public.ElectricPowerQuality (
	 MeasurePointID      	INT         	NOT NULL
	,DataDate            	TIMESTAMPTZ 	NOT NULL
	,Pp                  	REAL
	,Pn                  	REAL
	,Qp                  	REAL
	,Qn                  	REAL
	,CalculatedValues    	BIGINT
	,BadValues           	BIGINT
	,S                   	REAL
	,SA                  	REAL
	,SB                  	REAL
	,SC                  	REAL
	,PA                  	REAL
	,PB                  	REAL
	,PC                  	REAL
	,QA                  	REAL
	,QB                  	REAL
	,QC                  	REAL
	,U                   	REAL
	,UA                  	REAL
	,UB                  	REAL
	,UC                  	REAL
	,I                   	REAL
	,IA                  	REAL
	,IB                  	REAL
	,IC                  	REAL
	,PhiUAB              	REAL
	,PhiUAC              	REAL
	,PhiUBC              	REAL
	,PhiUIA              	REAL
	,PhiUIB              	REAL
	,PhiUIC              	REAL
	,Frequency           	REAL
	,P                   	REAL
	,Q                   	REAL
	,CosPhi              	REAL
	,CosPhiA             	REAL
	,CosPhiB             	REAL
	,CosPhiC             	REAL
);

DROP TABLE IF EXISTS public.ElectricTotals;
CREATE TABLE public.ElectricTotals (
	 MeasurePointId      	INT         	NOT NULL
	,DataDate            	TIMESTAMPTZ 	NOT NULL
	,Ap1                 	REAL
	,An1                 	REAL
	,Rp1                 	REAL
	,Rn1                 	REAL
	,Ap2                 	REAL
	,An2                 	REAL
	,Rp2                 	REAL
	,Rn2                 	REAL
	,Ap3                 	REAL
	,An3                 	REAL
	,Rp3                 	REAL
	,Rn3                 	REAL
	,Ap4                 	REAL
	,An4                 	REAL
	,Rp4                 	REAL
	,Rn4                 	REAL
	,Flags               	INT         	NOT NULL
	,CalculatedValues    	INT
	,BadValues           	INT
	,Ap                  	REAL
	,An                  	REAL
	,Rp                  	REAL
	,Rn                  	REAL
	,ResettedValues      	INT
	,InterpolatedValues  	INT
	,NormalOperationDuration	REAL
);

DROP TABLE IF EXISTS public.Equipment;
CREATE TABLE public.Equipment (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,EquipmentModelId    	INT         	NOT NULL
	,SerialNumber        	TEXT        	NOT NULL
	,LastCalibrationDate 	DATE
	,ScheduledCalibrationDate	DATE
	,ModificationId      	INT
	,Password            	TEXT        	NOT NULL
	,Comment             	TEXT        	NOT NULL
	,ModemIdentifier     	TEXT
	,ModemPollPortId     	INT
	,ModemIMEI           	TEXT
	,NetworkAddress      	TEXT
	,SecondLevelPassword 	TEXT
	,IsShared            	BOOLEAN     	NOT NULL
	,ModemEnableKeepAlive	BOOLEAN
	,DivisionId          	INT
);

DROP TABLE IF EXISTS public.EquipmentHistory;
CREATE TABLE public.EquipmentHistory (
	 Id                  	BIGINT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,DateTime            	TIMESTAMPTZ 	NOT NULL
	,NodeId              	INT         	NOT NULL
	,MeasurePointId      	INT
	,Action              	INT         	NOT NULL
	,EquipmentModelId    	INT         	NOT NULL
	,SerialNumber        	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.EquipmentModel;
CREATE TABLE public.EquipmentModel (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,IsSystem            	BOOLEAN     	NOT NULL
	,LongTitle           	TEXT        	NOT NULL
	,Title               	TEXT        	NOT NULL
	,Capabilities        	INT         	NOT NULL
	,Comment             	TEXT        	NOT NULL
	,SerialNumberFormat  	TEXT        	NOT NULL
	,SerialNumberComment 	TEXT        	NOT NULL
	,StateRegisterNumber 	TEXT        	NOT NULL
	,CalibrationInterval 	INT         	NOT NULL
	,IsTemperatureSensor 	BOOLEAN     	NOT NULL
	,IsPressureSensor    	BOOLEAN     	NOT NULL
	,IsFlowSensor        	BOOLEAN     	NOT NULL
	,SupportedSystemTypes	INT         	NOT NULL
	,SupportedCommLinks  	INT         	NOT NULL
	,SupportedCallTypes  	INT         	NOT NULL
	,ModemFeatures       	INT         	NOT NULL
	,DryContactCount     	INT         	NOT NULL
	,IsElectricMeter     	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.EquipmentModelAdapter;
CREATE TABLE public.EquipmentModelAdapter (
	 EquipmentModelId    	INT         	NOT NULL
	,AdapterId           	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.EquipmentModelModification;
CREATE TABLE public.EquipmentModelModification (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,EquipmentModelId    	INT         	NOT NULL
	,IsSystem            	BOOLEAN     	NOT NULL
	,Comment             	TEXT        	NOT NULL
	,PrecisionClass      	TEXT        	NOT NULL
	,NominalDiameter     	INT         	NOT NULL
	,RelativeError       	REAL        	NOT NULL
	,TempSensorMin       	REAL        	NOT NULL
	,TempSensorMax       	REAL        	NOT NULL
	,PressSensorMin      	REAL        	NOT NULL
	,PressSensorMax      	REAL        	NOT NULL
	,FlowSensorMin       	REAL        	NOT NULL
	,FlowSensorMax       	REAL        	NOT NULL
);

DROP TABLE IF EXISTS public.EquipmentModelPort;
CREATE TABLE public.EquipmentModelPort (
	 Id                  	INT         	NOT NULL
	,Title               	TEXT        	NOT NULL
	,EquipmentModelId    	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.EquipmentModelPortSettings;
CREATE TABLE public.EquipmentModelPortSettings (
	 Id                  	INT         	NOT NULL
	,Title               	TEXT        	NOT NULL
	,EquipmentModelPortId	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.EquipmentPollConnection;
CREATE TABLE public.EquipmentPollConnection (
	 EquipmentId         	INT         	NOT NULL
	,NodeId              	INT         	NOT NULL
	,PollConnectionId    	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.EquipmentPollStatistics;
CREATE TABLE public.EquipmentPollStatistics (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,EquipmentId         	INT         	NOT NULL
	,EndDate             	TIMESTAMPTZ 	NOT NULL
	,PollResult          	INT         	NOT NULL
	,PollType            	INT         	NOT NULL
	,CommLinkType        	INT         	NOT NULL
	,PollErrorCount      	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.GasConsumptionCurrent;
CREATE TABLE public.GasConsumptionCurrent (
	 MeasurePointID      	INT         	NOT NULL
	,DataDate            	TIMESTAMPTZ 	NOT NULL
	,T                   	REAL
	,P                   	REAL
	,V                   	REAL
	,V_std               	REAL
	,CalculatedValues    	INT
	,BadValues           	INT
	,T_outdoor           	REAL
	,M                   	REAL
	,P_delta             	REAL
);

DROP TABLE IF EXISTS public.GasConsumptionDay;
CREATE TABLE public.GasConsumptionDay (
	 MeasurePointID      	INT         	NOT NULL
	,DataDate            	TIMESTAMPTZ 	NOT NULL
	,T                   	REAL
	,P                   	REAL
	,V                   	REAL
	,V_std               	REAL
	,NormalOperationDuration	REAL
	,Attributes          	INT
	,CalculatedValues    	INT
	,BadValues           	INT
	,T_outdoor           	REAL
	,InterpolatedValues  	INT
	,M                   	REAL
	,P_delta             	REAL
);

DROP TABLE IF EXISTS public.GasConsumptionHour;
CREATE TABLE public.GasConsumptionHour (
	 MeasurePointID      	INT         	NOT NULL
	,DataDate            	TIMESTAMPTZ 	NOT NULL
	,T                   	REAL
	,P                   	REAL
	,V                   	REAL
	,V_std               	REAL
	,NormalOperationDuration	REAL
	,Attributes          	INT
	,CalculatedValues    	INT
	,BadValues           	INT
	,T_outdoor           	REAL
	,InterpolatedValues  	INT
	,M                   	REAL
	,P_delta             	REAL
);

DROP TABLE IF EXISTS public.GasConsumptionMonth;
CREATE TABLE public.GasConsumptionMonth (
	 MeasurePointID      	INT         	NOT NULL
	,DataDate            	TIMESTAMPTZ 	NOT NULL
	,T                   	REAL
	,P                   	REAL
	,V                   	REAL
	,V_std               	REAL
	,NormalOperationDuration	REAL
	,Attributes          	INT
	,CalculatedValues    	INT
	,BadValues           	INT
	,T_outdoor           	REAL
	,InterpolatedValues  	INT
	,M                   	REAL
	,P_delta             	REAL
);

DROP TABLE IF EXISTS public.GasTotals;
CREATE TABLE public.GasTotals (
	 MeasurePointId      	INT         	NOT NULL
	,DataDate            	TIMESTAMPTZ 	NOT NULL
	,V                   	REAL
	,V_std               	REAL
	,NormalOperationDuration	REAL
	,Flags               	INT         	NOT NULL
	,CalculatedValues    	INT
	,BadValues           	INT
	,ResettedValues      	INT
	,InterpolatedValues  	INT
	,M                   	REAL
);

DROP TABLE IF EXISTS public.GeneralDeviceConfigParam;
CREATE TABLE public.GeneralDeviceConfigParam (
	 Id                  	INT         	NOT NULL
	,Title               	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.GprsControllerSession;
CREATE TABLE public.GprsControllerSession (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,StartDateTime       	TIMESTAMPTZ 	NOT NULL
	,EndDateTime         	TIMESTAMPTZ
	,ControllerClock     	TIMESTAMPTZ
	,SignalLevel         	INT
	,HardwareVersion     	TEXT
	,FirmwareVersion     	TEXT
	,RemoteIPAddress     	TEXT        	NOT NULL
	,RemotePort          	INT         	NOT NULL
	,Balance             	REAL
	,BytesSent           	BIGINT      	NOT NULL
	,BytesReceived       	BIGINT      	NOT NULL
	,ICCID               	TEXT
	,ActiveSim           	INT
	,SimPinEnabled       	BOOLEAN
	,EquipmentId         	INT         	NOT NULL
	,EndReason           	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.HeatLoss;
CREATE TABLE public.HeatLoss (
	 MeasurePointId      	INT         	NOT NULL
	,Year                	INT         	NOT NULL
	,Jan                 	REAL
	,Feb                 	REAL
	,Mar                 	REAL
	,Apr                 	REAL
	,May                 	REAL
	,Jun                 	REAL
	,Jul                 	REAL
	,Aug                 	REAL
	,Sep                 	REAL
	,Oct                 	REAL
	,Nov                 	REAL
	,Dec                 	REAL
	,Percent             	REAL
	,Hour                	REAL
);

DROP TABLE IF EXISTS public.IncidentType;
CREATE TABLE public.IncidentType (
	 ID                  	INT         	NOT NULL
	,Title               	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.Inspector;
CREATE TABLE public.Inspector (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Name                	TEXT        	NOT NULL
	,Post                	TEXT        	NOT NULL
	,Phone               	TEXT        	NOT NULL
	,Email               	TEXT        	NOT NULL
	,Comment             	TEXT        	NOT NULL
	,SupplierId          	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.IPAddress;
CREATE TABLE public.IPAddress (
	 AccountId           	INT         	NOT NULL
	,RangeStartIp        	BIGINT      	NOT NULL
	,RangeEndIp          	BIGINT      	NOT NULL
);

DROP TABLE IF EXISTS public.LimitTemps;
CREATE TABLE public.LimitTemps (
	 TempIn              	INT
	,T0                  	INT
	,T2                  	INT
	,T4                  	INT
	,T6                  	INT
	,T8                  	INT
	,T10                 	INT
	,T12                 	INT
	,T14                 	INT
	,T16                 	INT
	,T18                 	INT
	,T20                 	INT
	,T22                 	INT
	,T24                 	INT
	,T26                 	INT
	,T28                 	INT
	,T30                 	INT
	,T32                 	INT
);

DROP TABLE IF EXISTS public.MailList;
CREATE TABLE public.MailList (
	 TaskID              	INT         	NOT NULL
	,SendSMS             	BOOLEAN     	NOT NULL
	,SendEmail           	BOOLEAN     	NOT NULL
	,AccountID           	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.Map;
CREATE TABLE public.Map (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Title               	TEXT        	NOT NULL
	,IsPublic            	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.MapImage;
CREATE TABLE public.MapImage (
	 Checksum            	INT         	NOT NULL
	,Image               	BYTEA       	NOT NULL
);

DROP TABLE IF EXISTS public.MapObject;
CREATE TABLE public.MapObject (
	 ID                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,MapID               	INT         	NOT NULL
	,MapObjectTypeID     	INT         	NOT NULL
	,MeasurePointID      	INT
	,X                   	INT         	NOT NULL
	,Y                   	INT         	NOT NULL
	,dX                  	INT         	NOT NULL
	,dY                  	INT         	NOT NULL
	,Text                	TEXT        	NOT NULL
	,Tag                 	TEXT        	NOT NULL
	,Image               	INT
	,Parameter           	TEXT
	,Locked              	BOOLEAN     	NOT NULL
	,ZOrder              	INT         	NOT NULL
	,NodeSignalingId     	INT
);

DROP TABLE IF EXISTS public.MapObjectAppearance;
CREATE TABLE public.MapObjectAppearance (
	 MapObjectId         	INT         	NOT NULL
	,AppearanceType      	INT         	NOT NULL
	,BorderColor         	INT         	NOT NULL
	,BorderWidth         	INT         	NOT NULL
	,FillColor           	INT         	NOT NULL
	,FontColor           	INT         	NOT NULL
	,FontSize            	REAL        	NOT NULL
	,FontFamily          	TEXT        	NOT NULL
	,FontStyle           	INT         	NOT NULL
	,TextVAlignment      	INT         	NOT NULL
	,TextHAlignment      	INT         	NOT NULL
	,Visible             	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.MapObjectType;
CREATE TABLE public.MapObjectType (
	 ID                  	INT         	NOT NULL
	,Title               	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.MeasuredParameter;
CREATE TABLE public.MeasuredParameter (
	 MeasuredParameter_ID	INT         	NOT NULL
	,MeasuredParameter_Title	TEXT        	NOT NULL
	,MeasuredParameter_SystemUnitID	INT
	,MeasuredParameter_Code	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.MeasurePoint;
CREATE TABLE public.MeasurePoint (
	 MeasurePoint_ID     	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,MeasurePoint_Title  	TEXT        	NOT NULL
	,MeasurePoint_ServiceNumber	INT         	NOT NULL
	,MeasurePoint_Comment	TEXT        	NOT NULL
	,MeasurePoint_Type   	INT         	NOT NULL
	,MeasurePoint_State  	INT         	NOT NULL  DEFAULT 0
	,MeasurePoint_SelectedParamsList	TEXT        	NOT NULL
	,MeasurePoint_NodeID 	INT
	,MeasurePoint_SystemTypeID	INT         	NOT NULL
	,AutoPollStartDate   	TIMESTAMPTZ
	,IsDoublePipeSystem  	BOOLEAN     	NOT NULL
	,PersonalAccountID   	INT
	,ContractHeat        	REAL        	NOT NULL
	,ContractFlow        	REAL        	NOT NULL
	,CurrentRatio        	REAL        	NOT NULL
	,VoltageRatio        	REAL        	NOT NULL
	,ContractPin         	REAL        	NOT NULL
	,ContractPout        	REAL        	NOT NULL
	,ContractTin         	REAL        	NOT NULL
	,ContractTout        	REAL        	NOT NULL
	,ShowCalculatedData  	BOOLEAN     	NOT NULL
	,DevicePressureType  	INT         	NOT NULL
	,CounterId           	INT
	,CalculateMissingTotals	BOOLEAN     	NOT NULL
	,CalculateMissingTotalsEstimate	BOOLEAN     	NOT NULL
	,CalculateMissingHourConsumption	INT         	NOT NULL
	,CalculateMissingDayConsumption	INT         	NOT NULL
	,CalculateMissingMonthConsumption	INT         	NOT NULL
	,CalculateMissingValues	BOOLEAN     	NOT NULL
	,ReportingHour       	INT         	NOT NULL
	,ReportingDay        	INT         	NOT NULL
	,ShowBadValues       	BOOLEAN     	NOT NULL
	,CalculateMissingHeatValues	BOOLEAN     	NOT NULL
	,CalculatedValuesAveragingMode	INT         	NOT NULL
	,IsReversibleFlow    	BOOLEAN     	NOT NULL
	,ReportingHourMode   	INT         	NOT NULL
	,IsVirtual           	BOOLEAN     	NOT NULL
	,UseAdvancedTotalsInterpolation	BOOLEAN     	NOT NULL
	,DiagDataTypes       	INT
	,DisplayPressureType 	INT         	NOT NULL
	,AdmissionDate       	TIMESTAMPTZ
);

DROP TABLE IF EXISTS public.MeasurePointCustomAttribute;
CREATE TABLE public.MeasurePointCustomAttribute (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,CustomAttributeId   	INT         	NOT NULL
	,MeasurePointId      	INT         	NOT NULL
	,Value               	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.MeasurePointDataCopySettings;
CREATE TABLE public.MeasurePointDataCopySettings (
	 TargetMeasurePointId	INT         	NOT NULL
	,WaterParameter      	INT         	NOT NULL
	,SourceMeasurePointId	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.MeasurePointDeviceErrorDay;
CREATE TABLE public.MeasurePointDeviceErrorDay (
	 MeasurePointId      	INT         	NOT NULL
	,ArchiveType         	INT         	NOT NULL
	,ChannelNumber       	INT         	NOT NULL
	,DateTime            	TIMESTAMPTZ 	NOT NULL
	,EventCode           	INT         	NOT NULL
	,Description         	TEXT        	NOT NULL
	,Duration            	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.MeasurePointDeviceErrorHour;
CREATE TABLE public.MeasurePointDeviceErrorHour (
	 MeasurePointId      	INT         	NOT NULL
	,ArchiveType         	INT         	NOT NULL
	,ChannelNumber       	INT         	NOT NULL
	,DateTime            	TIMESTAMPTZ 	NOT NULL
	,EventCode           	INT         	NOT NULL
	,Description         	TEXT        	NOT NULL
	,Duration            	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.MeasurePointDeviceErrorMonth;
CREATE TABLE public.MeasurePointDeviceErrorMonth (
	 MeasurePointId      	INT         	NOT NULL
	,ArchiveType         	INT         	NOT NULL
	,ChannelNumber       	INT         	NOT NULL
	,DateTime            	TIMESTAMPTZ 	NOT NULL
	,EventCode           	INT         	NOT NULL
	,Description         	TEXT        	NOT NULL
	,Duration            	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.MeasurePointDiagDefaults;
CREATE TABLE public.MeasurePointDiagDefaults (
	 SystemTypeID        	INT         	NOT NULL
	,IncidentTypeId      	INT         	NOT NULL
	,IsEnabled           	BOOLEAN     	NOT NULL
	,Value1              	REAL        	NOT NULL
	,Value2              	REAL        	NOT NULL
	,IsSummerMode        	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.MeasurePointDiagParams;
CREATE TABLE public.MeasurePointDiagParams (
	 MeasurePointID      	INT         	NOT NULL
	,IncidentTypeId      	INT         	NOT NULL
	,IsEnabled           	BOOLEAN     	NOT NULL
	,Value1              	REAL        	NOT NULL
	,Value2              	REAL        	NOT NULL
	,IsSummerMode        	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.MeasurePointExpression;
CREATE TABLE public.MeasurePointExpression (
	 MeasurePointId      	INT         	NOT NULL
	,DataParameter       	INT         	NOT NULL
	,Expression          	VARCHAR     	NOT NULL
);

DROP TABLE IF EXISTS public.MeasurePointOrder;
CREATE TABLE public.MeasurePointOrder (
	 MeasurePointID      	INT         	NOT NULL
	,OrderNumber         	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.MeasurePointReport;
CREATE TABLE public.MeasurePointReport (
	 MeasurePointId      	INT         	NOT NULL
	,ReportId            	INT         	NOT NULL
	,ReportTemplateId    	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.MeasurePointSensor;
CREATE TABLE public.MeasurePointSensor (
	 MeasurePointId      	INT         	NOT NULL
	,IsSupplyChannel     	BOOLEAN     	NOT NULL
	,MeasuredParameterId 	INT         	NOT NULL
	,EquipmentId         	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.MessageLog;
CREATE TABLE public.MessageLog (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Date                	TIMESTAMPTZ 	NOT NULL
	,SenderAccountId     	INT
	,SenderName          	TEXT        	NOT NULL
	,RecipientName       	TEXT        	NOT NULL
	,RecipientAddress    	TEXT        	NOT NULL
	,Message             	VARCHAR     	NOT NULL
	,MessageType         	INT         	NOT NULL
	,SendResult          	TEXT        	NOT NULL
	,SendState           	INT         	NOT NULL
	,SendScheduleDate    	TIMESTAMPTZ 	NOT NULL
);

DROP TABLE IF EXISTS public.ModemCommand;
CREATE TABLE public.ModemCommand (
	 ModemCommand_ModemTypeID	INT         	NOT NULL
	,ModemCommand_ModemCommandTypeID	INT         	NOT NULL
	,ModemCommand_Text   	TEXT        	NOT NULL
	,ModemCommand_TerminationType	INT         	NOT NULL  DEFAULT 2
	,ModemCommand_DelayBefore	INT         	NOT NULL
	,ModemCommand_Timeout	INT         	NOT NULL
	,ModemCommand_BadAnswerList	TEXT        	NOT NULL
	,ModemCommand_GoodAnswerList	TEXT        	NOT NULL
	,ModemCommand_Comment	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.ModemCommandType;
CREATE TABLE public.ModemCommandType (
	 ModemCommandType_ID 	INT         	NOT NULL
	,ModemCommandType_Title	TEXT        	NOT NULL
	,ModemCommandType_Code	TEXT        	NOT NULL
	,ModemCommandType_Comment	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.ModemType;
CREATE TABLE public.ModemType (
	 ModemType_ID        	INT         	NOT NULL
	,ModemType_Title     	TEXT        	NOT NULL
	,ModemType_CommunicationLinkType	INT         	NOT NULL
	,ModemType_DataTransferDelay	INT         	NOT NULL
	,ModemType_PortSettings	TEXT        	NOT NULL
	,ModemType_MaxCommandLen	INT         	NOT NULL
	,ModemType_ShieldCode	INT
);

DROP TABLE IF EXISTS public.NestedBalanceGroups;
CREATE TABLE public.NestedBalanceGroups (
	 ParentId            	INT         	NOT NULL
	,ChildId             	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.Node;
CREATE TABLE public.Node (
	 ID                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Title               	TEXT        	NOT NULL
	,Address             	TEXT        	NOT NULL
	,Comment             	TEXT        	NOT NULL
	,Number              	INT         	NOT NULL
	,CustomerID          	INT
	,ResponsibleName     	TEXT        	NOT NULL
	,ResponsiblePhone    	TEXT        	NOT NULL
	,ServiceCompanyID    	INT
	,State               	INT         	NOT NULL
	,ServicemanID        	INT
	,Type                	INT         	NOT NULL
	,NormColdWater       	REAL        	NOT NULL
	,NormHotWater        	REAL        	NOT NULL
	,NormHeat            	REAL        	NOT NULL
	,NormElectricity     	REAL        	NOT NULL
	,NormGas             	REAL        	NOT NULL
	,IsCommunalPollEnabled	BOOLEAN     	NOT NULL
	,TimeZoneOffset      	INT         	NOT NULL
	,ColdWaterTemp       	REAL        	NOT NULL
	,LicenseCount        	INT         	NOT NULL
	,ContractMinTemp     	INT         	NOT NULL  DEFAULT 70
	,ContractMaxTemp     	INT         	NOT NULL  DEFAULT 130
	,ContractLowBreakTemp	INT         	NOT NULL  DEFAULT 0
	,ContractHighBreakTemp	INT         	NOT NULL  DEFAULT 0
	,MinOutdoorTemp      	INT         	NOT NULL  -- DEFAULT ((-31))
	,TemperatureComplianceAnalysisType	INT         	NOT NULL  DEFAULT 0
	,TerritoryId         	INT         	NOT NULL  DEFAULT 0
	,DivisionId          	INT
);

DROP TABLE IF EXISTS public.NodeBalance;
CREATE TABLE public.NodeBalance (
	 ID                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,NodeID              	INT         	NOT NULL
	,Symbol              	TEXT        	NOT NULL
	,Expression          	VARCHAR     	NOT NULL
);

DROP TABLE IF EXISTS public.NodeCustomAttribute;
CREATE TABLE public.NodeCustomAttribute (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,NodeId              	INT         	NOT NULL
	,CustomAttributeId   	INT         	NOT NULL
	,Value               	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.NodeDiagDefaults;
CREATE TABLE public.NodeDiagDefaults (
	 IncidentTypeId      	INT         	NOT NULL
	,IsEnabled           	BOOLEAN     	NOT NULL
	,Value1              	REAL        	NOT NULL
	,Value2              	REAL        	NOT NULL
);

DROP TABLE IF EXISTS public.NodeDiagParams;
CREATE TABLE public.NodeDiagParams (
	 NodeID              	INT         	NOT NULL
	,IncidentTypeId      	INT         	NOT NULL
	,IsEnabled           	BOOLEAN     	NOT NULL
	,Value1              	REAL        	NOT NULL
	,Value2              	REAL        	NOT NULL
);

DROP TABLE IF EXISTS public.NodeEquipment;
CREATE TABLE public.NodeEquipment (
	 NodeId              	INT         	NOT NULL
	,EquipmentId         	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.NodeFile;
CREATE TABLE public.NodeFile (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,NodeId              	INT         	NOT NULL
	,FileName            	TEXT        	NOT NULL
	,CreationTime        	TIMESTAMPTZ 	NOT NULL
	,LastWriteTime       	TIMESTAMPTZ 	NOT NULL
	,Content             	BYTEA       	NOT NULL
	,Hash                	BYTEA       	NOT NULL
	,PublicFile          	BOOLEAN     	NOT NULL  DEFAULT true
	,Thumbnail           	BYTEA
	,Length              	BIGINT        -- COMPUTED (datalength([Content]))
);

DROP TABLE IF EXISTS public.NodeGeoLocation;
CREATE TABLE public.NodeGeoLocation (
	 NodeId              	INT         	NOT NULL
	,Latitude            	REAL        	NOT NULL
	,Longitude           	REAL        	NOT NULL
);

DROP TABLE IF EXISTS public.NodeGroup;
CREATE TABLE public.NodeGroup (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Title               	TEXT        	NOT NULL
	,Comment             	TEXT        	NOT NULL
	,DivisionId          	INT
);

DROP TABLE IF EXISTS public.NodeGroupMembership;
CREATE TABLE public.NodeGroupMembership (
	 NodeGroupId         	INT         	NOT NULL
	,NodeId              	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.NodeJob;
CREATE TABLE public.NodeJob (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,NodeId              	INT         	NOT NULL
	,MeasurePointId      	INT
	,CreatorAccountId    	INT
	,CreatorName         	TEXT        	NOT NULL  DEFAULT ''
	,PerformerAccountId  	INT
	,PerformerName       	TEXT        	NOT NULL  DEFAULT ''
	,StartDate           	DATE        	NOT NULL
	,ScheduledEndDate    	DATE        	NOT NULL
	,FactEndDate         	DATE
	,Title               	TEXT        	NOT NULL
	,Description         	TEXT        	NOT NULL  DEFAULT ''
	,State               	INT         	NOT NULL
	,Type                	INT         	NOT NULL
	,ResolutionId        	INT
	,IncidentId          	INT
	,WorkOrderNumber     	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.NodeJobComment;
CREATE TABLE public.NodeJobComment (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,NodeJobId           	INT         	NOT NULL
	,DateTime            	TIMESTAMPTZ 	NOT NULL
	,AccountId           	INT
	,AccountName         	TEXT        	NOT NULL
	,Text                	VARCHAR
);

DROP TABLE IF EXISTS public.NodeJobFile;
CREATE TABLE public.NodeJobFile (
	 NodeJobId           	INT         	NOT NULL
	,NodeFileId          	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.NodeJobResolution;
CREATE TABLE public.NodeJobResolution (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Title               	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.NodePollConnection;
CREATE TABLE public.NodePollConnection (
	 PollConnectionId    	INT         	NOT NULL
	,NodeId              	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.NodeReport;
CREATE TABLE public.NodeReport (
	 NodeId              	INT         	NOT NULL
	,ReportId            	INT         	NOT NULL
	,ReportTemplateId    	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.NodeSeasonHistory;
CREATE TABLE public.NodeSeasonHistory (
	 NodeId              	INT         	NOT NULL
	,StartDate           	DATE        	NOT NULL
	,IsHeatingSeason     	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.NodeSignaling;
CREATE TABLE public.NodeSignaling (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,NodeId              	INT         	NOT NULL
	,SignalTitle         	TEXT        	NOT NULL
	,DryContactNumber    	INT         	NOT NULL
	,IncidentImportanceSet	INT         	NOT NULL
	,IncidentMessageSet  	TEXT        	NOT NULL
	,IncidentImportanceUnset	INT         	NOT NULL
	,IncidentMessageUnset	TEXT        	NOT NULL
	,CurrentState        	INT         	NOT NULL  DEFAULT 0
	,EquipmentId         	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.NodeSupplier;
CREATE TABLE public.NodeSupplier (
	 NodeId              	INT         	NOT NULL
	,SystemType          	INT         	NOT NULL
	,SupplierId          	INT
	,ContractNumber      	TEXT        	NOT NULL
	,ContractDate        	TIMESTAMPTZ
	,InspectorId         	INT
);

DROP TABLE IF EXISTS public.NodeUserDiagParams;
CREATE TABLE public.NodeUserDiagParams (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,NodeId              	INT         	NOT NULL
	,Expression          	VARCHAR     	NOT NULL
	,Seasons             	INT         	NOT NULL
	,DataTypes           	INT         	NOT NULL
	,Message             	TEXT        	NOT NULL
	,Enabled             	BOOLEAN     	NOT NULL
	,Importance          	INT         	NOT NULL
	,ShortMessage        	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.Notification;
CREATE TABLE public.Notification (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,NotificationTypeId  	INT         	NOT NULL
	,DateTime            	TIMESTAMPTZ 	NOT NULL
	,Message             	TEXT        	NOT NULL
	,Importance          	INT         	NOT NULL
	,ExpiredDate         	DATE
	,EquipmentId         	INT
	,IncidentId          	INT
	,NodeJobId           	INT
	,Url                 	TEXT
	,MeasurePointId      	INT
);

DROP TABLE IF EXISTS public.NotificationType;
CREATE TABLE public.NotificationType (
	 Id                  	INT         	NOT NULL
	,Title               	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.OutdoorTemperature;
CREATE TABLE public.OutdoorTemperature (
	 Date                	TIMESTAMPTZ 	NOT NULL
	,Value               	REAL        	NOT NULL
	,TerritoryId         	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.PersonalAccount;
CREATE TABLE public.PersonalAccount (
	 PersonalAccount_ID  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,PersonalAccount_Number	TEXT        	NOT NULL
	,PersonalAccount_NumberApartment	TEXT        	NOT NULL
	,PersonalAccount_NumberResident	INT         	NOT NULL
	,PersonalAccount_AreaApartment	REAL        	NOT NULL
	,NodeId              	INT         	NOT NULL
	,Type                	INT         	NOT NULL
	,ContractHotWater    	REAL        	NOT NULL
	,ContractColdWater   	REAL        	NOT NULL
	,ContractGas         	REAL        	NOT NULL
	,ContractElectricity 	REAL        	NOT NULL
	,ContractHeat        	REAL        	NOT NULL
	,ContractConsumptionType	INT         	NOT NULL
	,FloorNumber         	INT         	NOT NULL
	,RoomCount           	INT         	NOT NULL
	,EntranceNumber      	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.Plugin;
CREATE TABLE public.Plugin (
	 Identifier          	CHAR(36)    	NOT NULL
	,FileName            	TEXT        	NOT NULL
	,IsDisabled          	BOOLEAN     	NOT NULL
	,Settings            	VARCHAR     	NOT NULL
);

DROP TABLE IF EXISTS public.PollConnection;
CREATE TABLE public.PollConnection (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Title               	TEXT        	NOT NULL
	,CommLinkType        	INT         	NOT NULL
	,PollPortId          	INT
	,PollPortGroupId     	INT
	,CommDeviceEquipmentId	INT
	,CommDevicePortId    	INT
	,CommDevicePortSettingsId	INT
	,ConnectionTimeout   	INT
	,DialNumber          	TEXT
	,CommLinkProtocol    	INT         	NOT NULL
	,GprsCallType        	INT         	NOT NULL
	,GprsAutoDisconnect  	BOOLEAN     	NOT NULL
	,InternetHost        	TEXT        	NOT NULL
	,InternetPort        	INT         	NOT NULL
	,ImitateModem        	BOOLEAN     	NOT NULL
	,PortSpeed           	INT         	NOT NULL
	,FlowControl         	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.PollPort;
CREATE TABLE public.PollPort (
	 PollPort_ID         	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,PollPort_PortNumber 	INT         	NOT NULL
	,PollPort_Enabled    	BOOLEAN     	NOT NULL
	,PollPort_Title      	TEXT        	NOT NULL
	,PollPort_DialPrefix 	TEXT        	NOT NULL
	,PollPort_CommunicationLinkType	INT         	NOT NULL
	,PollPort_ModemTypeID	INT         	NOT NULL
	,GprsListenIPAddress 	TEXT        	NOT NULL
	,GprsListenPort      	INT         	NOT NULL
	,MaxConnectionsCount 	INT         	NOT NULL
	,SoftwareCarrierControl	BOOLEAN     	NOT NULL
	,Comment             	TEXT        	NOT NULL
	,PollPortGroupId     	INT
	,BillingModel        	INT         	NOT NULL
	,TariffPlanIncludedMinutes	INT         	NOT NULL
	,PollServiceId       	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.PollPortGroup;
CREATE TABLE public.PollPortGroup (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Title               	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.PollPortStatistics;
CREATE TABLE public.PollPortStatistics (
	 PollPortId          	INT         	NOT NULL
	,Date                	DATE        	NOT NULL
	,CallCount           	INT         	NOT NULL
	,TotalCallsDuration  	INT         	NOT NULL
	,Traffic             	BIGINT      	NOT NULL
);

DROP TABLE IF EXISTS public.PollService;
CREATE TABLE public.PollService (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Title               	TEXT        	NOT NULL
	,IpAddress           	TEXT        	NOT NULL
	,DebugEnabled        	BOOLEAN     	NOT NULL
	,Token               	TEXT
);

DROP TABLE IF EXISTS public.PollSession;
CREATE TABLE public.PollSession (
	 PollSession_ID      	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,PollSession_ClientSessionID	INT         	NOT NULL
	,PollSession_TaskID  	INT
	,PollSession_StartDatetime	TIMESTAMPTZ 	NOT NULL
	,PollSession_EndDatetime	TIMESTAMPTZ
	,PollSession_ResultCode	INT
	,PollSession_CommunicationLinkType	INT         	NOT NULL
	,DialTime            	REAL        	NOT NULL
	,PollPortId          	INT
	,NodeId              	INT
	,PhoneNumber         	TEXT        	NOT NULL
	,PollTaskType        	INT         	NOT NULL
	,CallDuration        	INT         	NOT NULL
	,BytesSent           	BIGINT      	NOT NULL
	,BytesReceived       	BIGINT      	NOT NULL
	,CommEquipmentId     	INT
	,PollConnectionId    	INT
);

DROP TABLE IF EXISTS public.PollSessionLog;
CREATE TABLE public.PollSessionLog (
	 PollSessionLog_PollSessionID	INT         	NOT NULL
	,PollSessionLog_DataDate	TIMESTAMPTZ 	NOT NULL
	,PollSessionLog_Type 	INT         	NOT NULL
	,PollSessionLog_Message	VARCHAR     	NOT NULL
);

DROP TABLE IF EXISTS public.PollTask;
CREATE TABLE public.PollTask (
	 ID                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Description         	TEXT        	NOT NULL  DEFAULT ''
	,StartDatetime       	TIMESTAMPTZ 	NOT NULL
	,EndDatetime         	TIMESTAMPTZ 	NOT NULL
	,ExecutionState      	INT         	NOT NULL  DEFAULT 1
	,MaxAttempts         	INT         	NOT NULL  DEFAULT 1
	,Attempt             	INT         	NOT NULL  DEFAULT 0
	,LastAttemptTime     	TIMESTAMPTZ
	,LastAttemptResultCode	INT
	,NextAttemptDelay    	INT         	NOT NULL  DEFAULT 3600
	,FreqType            	INT         	NOT NULL  DEFAULT 4
	,FreqInterval        	INT         	NOT NULL  DEFAULT 1
	,StartTime           	INT         	NOT NULL  DEFAULT 0
	,RetryInterval       	INT         	NOT NULL  DEFAULT 0
	,EndTime             	INT         	NOT NULL  DEFAULT 1439
	,PollIntervalStartDate	TIMESTAMPTZ
	,PollIntervalEndDate 	TIMESTAMPTZ
	,PollInstantInterval 	INT         	NOT NULL  DEFAULT 10
	,RemoteConsoleMode   	BOOLEAN     	NOT NULL  DEFAULT false
	,LastAttemptEndTime  	TIMESTAMPTZ
	,Priority            	INT         	NOT NULL  DEFAULT 3
	,Type                	INT         	NOT NULL
	,LoadAbsentDataOnly  	BOOLEAN     	NOT NULL
	,PollConnectionId    	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.PollTaskMeasurePoint;
CREATE TABLE public.PollTaskMeasurePoint (
	 TaskID              	INT         	NOT NULL
	,MeasurePointID      	INT         	NOT NULL
	,PerformTimeCorrection	BOOLEAN     	NOT NULL
	,RequestedDataMask   	INT         	NOT NULL
	,BackupConnectionId  	INT
	,BackupLastPollDate  	TIMESTAMPTZ
	,BackupStartTime     	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.PreparedReport;
CREATE TABLE public.PreparedReport (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,GenerationDateTime  	TIMESTAMPTZ 	NOT NULL
	,ReportTitle         	TEXT        	NOT NULL
	,TemplateTitle       	TEXT        	NOT NULL
	,ReportType          	INT         	NOT NULL
	,ReportEntity        	INT         	NOT NULL
	,NodeId              	INT
	,MeasurePointId      	INT
	,DataType            	INT         	NOT NULL
	,StartDate           	TIMESTAMPTZ 	NOT NULL
	,EndDate             	TIMESTAMPTZ 	NOT NULL
	,Data                	BYTEA       	NOT NULL
	,Thumbnail           	BYTEA       	NOT NULL
	,FileName            	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.ProtocolType;
CREATE TABLE public.ProtocolType (
	 ID                  	INT         	NOT NULL
	,Number              	INT         	NOT NULL
	,Title               	TEXT        	NOT NULL
	,EquipmentModelId    	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.Report;
CREATE TABLE public.Report (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Title               	TEXT        	NOT NULL
	,IsSystem            	BOOLEAN     	NOT NULL
	,DataType            	INT         	NOT NULL
	,ReportType          	INT         	NOT NULL
	,PeriodStartDay      	INT         	NOT NULL
	,PeriodStartMonth    	INT         	NOT NULL
	,PeriodEndDay        	INT         	NOT NULL
	,PeriodEndMonth      	INT         	NOT NULL
	,PeriodType          	INT         	NOT NULL
	,ReportEntity        	INT         	NOT NULL
	,ReportTemplateId    	INT
	,FileNameFormat      	TEXT        	NOT NULL  DEFAULT ''
	,UseReportParameter  	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.ReportFixedNode;
CREATE TABLE public.ReportFixedNode (
	 ReportTemplateId    	INT         	NOT NULL
	,NodeId              	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.ReportGeneratingTaskNode;
CREATE TABLE public.ReportGeneratingTaskNode (
	 TaskId              	INT         	NOT NULL
	,NodeId              	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.ReportGeneratingTaskSettings;
CREATE TABLE public.ReportGeneratingTaskSettings (
	 TaskId              	INT         	NOT NULL
	,MeasurePointSystems 	INT         	NOT NULL
	,ReportId            	INT         	NOT NULL
	,MailingFileFormat   	INT         	NOT NULL
	,MailingFileSplitMode	INT         	NOT NULL
	,MailSubject         	TEXT        	NOT NULL
	,SaveReport          	BOOLEAN     	NOT NULL
	,MailingEnabled      	BOOLEAN     	NOT NULL
	,MailMessage         	TEXT        	NOT NULL  DEFAULT ''
	,PdfExportProperties 	VARCHAR     	NOT NULL  DEFAULT ''
	,ReportSaveDirectory 	TEXT        	NOT NULL  DEFAULT ''
	,PackAttachments     	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.ReportParameter;
CREATE TABLE public.ReportParameter (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,ReportId            	INT         	NOT NULL
	,ReportParameterPropertyId	INT         	NOT NULL
	,Value               	TEXT        	NOT NULL  DEFAULT ''
);

DROP TABLE IF EXISTS public.ReportParameterProperty;
CREATE TABLE public.ReportParameterProperty (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,ParameterName       	TEXT        	NOT NULL
	,ValueType           	INT         	NOT NULL
	,Comment             	TEXT        	NOT NULL
	,ReportType          	INT         	NOT NULL
	,ReportEntity        	INT         	NOT NULL
	,IsSystem            	BOOLEAN     	NOT NULL
);

DROP TABLE IF EXISTS public.ReportTemplate;
CREATE TABLE public.ReportTemplate (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Title               	TEXT        	NOT NULL
	,Comment             	TEXT        	NOT NULL
	,IsUser              	BOOLEAN     	NOT NULL
	,DataSourceMask      	BIGINT      	NOT NULL
	,Text                	VARCHAR
	,ReportEntity        	INT         	NOT NULL
	,ReportType          	INT         	NOT NULL
	,MeasurePointCountHeat	INT         	NOT NULL  DEFAULT 0
	,MeasurePointCountHotWater	INT         	NOT NULL  DEFAULT 0
	,MeasurePointCountColdWater	INT         	NOT NULL  DEFAULT 0
	,MeasurePointCountSteam	INT         	NOT NULL  DEFAULT 0
	,MeasurePointCountGas	INT         	NOT NULL  DEFAULT 0
	,MeasurePointCountElectricity	INT         	NOT NULL  DEFAULT 0
	,BuildNumber         	INT         	NOT NULL  DEFAULT 0
	,EstimationAlgorithm 	INT         	NOT NULL  DEFAULT 0
	,DailyAverageCalculatingPeriod	INT         	NOT NULL  DEFAULT 0
	,DeviceModel         	INT         	NOT NULL  DEFAULT 0
	,MeasurePointCountSewage	INT         	NOT NULL  DEFAULT 0
);

DROP TABLE IF EXISTS public.RoomContractConsumption;
CREATE TABLE public.RoomContractConsumption (
	 RoomId              	INT         	NOT NULL
	,MonthNumber         	INT         	NOT NULL
	,HeatValue           	REAL
	,HotWaterValue       	REAL
	,ColdWaterValue      	REAL
	,ElectricityValue    	REAL
);

DROP TABLE IF EXISTS public.RoomCounter;
CREATE TABLE public.RoomCounter (
	 EquipmentId         	INT         	NOT NULL
	,RoomId              	INT         	NOT NULL
	,InitialTotalsValue1 	REAL        	NOT NULL
	,InitialTotalsValue2 	REAL        	NOT NULL
	,InitialTotalsDate   	TIMESTAMPTZ 	NOT NULL
	,InstallLocation     	TEXT        	NOT NULL
	,MeasurePointId      	INT
);

DROP TABLE IF EXISTS public.ScmMeasurePoints;
CREATE TABLE public.ScmMeasurePoints (
	 MeasurePointId      	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.ServiceCompany;
CREATE TABLE public.ServiceCompany (
	 ID                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Title               	TEXT        	NOT NULL
	,Phone               	TEXT        	NOT NULL
	,LicenseNumber       	TEXT        	NOT NULL
	,Comment             	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.Serviceman;
CREATE TABLE public.Serviceman (
	 ID                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Name                	TEXT        	NOT NULL
	,ServiceCompanyID    	INT
	,Phone               	TEXT        	NOT NULL  DEFAULT ''
	,Email               	TEXT        	NOT NULL  DEFAULT ''
	,Comment             	TEXT        	NOT NULL  DEFAULT ''
);

DROP TABLE IF EXISTS public.Supplier;
CREATE TABLE public.Supplier (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,Title               	TEXT        	NOT NULL
	,SystemTypeMask      	INT         	NOT NULL
	,Contacts            	TEXT        	NOT NULL
	,Comment             	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.SystemLog;
CREATE TABLE public.SystemLog (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,DateTime            	TIMESTAMPTZ 	NOT NULL
	,Importance          	INT         	NOT NULL
	,Message             	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.SystemParameters;
CREATE TABLE public.SystemParameters (
	 LogDebugMessages    	BOOLEAN     	NOT NULL
	,PollLogStorageTime  	INT         	NOT NULL
	,SystemLogStorageTime	INT         	NOT NULL
	,UserSessionLogStorageTime	INT         	NOT NULL
	,AccountLogStorageTime	INT         	NOT NULL
	,EmailLogStorageTime 	INT         	NOT NULL
	,IsAutoPollEnabled   	BOOLEAN     	NOT NULL
	,PollLogLevel        	INT         	NOT NULL
	,PollMaxDuration     	INT         	NOT NULL
	,PollMaxTimeDiff     	INT         	NOT NULL
	,DeviceRequestRetryCount	INT         	NOT NULL
	,PollPortBlockErrorCount	INT         	NOT NULL
	,PollPortBlockTimeout	INT         	NOT NULL
	,TimeCorrectionEnabled	BOOLEAN     	NOT NULL
	,TimeCorrectionThreshold	INT         	NOT NULL
	,GsmModemEnabled     	BOOLEAN     	NOT NULL
	,GsmModemComPortNumber	INT         	NOT NULL
	,GsmModemBaudRate    	INT         	NOT NULL
	,GsmModemFlowControl 	INT         	NOT NULL
	,DefaultSupplyPressure	INT         	NOT NULL
	,DefaultReturnPressure	INT         	NOT NULL
	,DefaultColdWaterTemp	REAL        	NOT NULL
	,PressureDisplayType 	INT         	NOT NULL
	,StorageTimeCurrentData	INT         	NOT NULL
	,MaxPartCountInMultipartSms	INT         	NOT NULL
	,SmtpServer          	TEXT        	NOT NULL
	,SmtpPort            	INT         	NOT NULL
	,SmtpSenderAddress   	TEXT        	NOT NULL
	,SmtpSenderDisplayName	TEXT        	NOT NULL
	,SmtpLogin           	TEXT        	NOT NULL
	,SmtpPassword        	TEXT        	NOT NULL
	,IsCommunalEnabled   	BOOLEAN     	NOT NULL
	,DiagEnabled         	BOOLEAN     	NOT NULL
	,DiagDayDataEnabled  	BOOLEAN     	NOT NULL
	,DiagHourDataEnabled 	BOOLEAN     	NOT NULL
	,DiagCurrentDataEnabled	BOOLEAN     	NOT NULL
	,StorageTimeMonthData	INT         	NOT NULL
	,StorageTimeDayData  	INT         	NOT NULL
	,StorageTimeHourData 	INT         	NOT NULL
	,StorageTimeDeviceConfig	INT         	NOT NULL
	,StorageTimeDeviceEvent	INT         	NOT NULL
	,StorageTimePowerData	INT         	NOT NULL
	,WebSiteAddress      	TEXT        	NOT NULL
	,SmtpEnableSsl       	BOOLEAN     	NOT NULL
	,IgnoreNotAllDataReadError	BOOLEAN     	NOT NULL
	,BackupDirectory     	TEXT        	NOT NULL  DEFAULT ''
	,UpdaterDataBaseBackupMode	INT         	NOT NULL
	,StorageTimeTotalsData	INT         	NOT NULL
	,BackupCount         	INT         	NOT NULL
	,CalibrationNotifyDayCount	INT         	NOT NULL
	,JobDueDateNotifyDayCount	INT         	NOT NULL
	,AllowSmsNotifications	BOOLEAN     	NOT NULL
	,GsmModemModelId     	INT         	NOT NULL
	,StorageTimePreparedReports	INT         	NOT NULL
	,Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,StorageTimeIncidents	INT         	NOT NULL
	,StorageTimeGprsSessions	INT         	NOT NULL
	,AllowedNodeFileExtensions	TEXT
	,MinimumPasswordLength	INT         	NOT NULL
	,PasswordMustContainNumbers	BOOLEAN     	NOT NULL
	,PasswordMustContainUppercaseLetters	BOOLEAN     	NOT NULL
	,PasswordMustContainLowercaseLetters	BOOLEAN     	NOT NULL
	,PasswordMustContainSpecialChars	BOOLEAN     	NOT NULL
	,GsmModem_UseSipForVoiceCalls	BOOLEAN     	NOT NULL
	,GsmModem_SipServerAddress	VARCHAR     	NOT NULL
	,GsmModem_SipLogin   	TEXT        	NOT NULL
	,GsmModem_SipPassword	TEXT        	NOT NULL
	,GsmModem_SipFromDomain	VARCHAR     	NOT NULL
	,SaveGeneratedReportToDataBase	BOOLEAN     	NOT NULL
	,Log_SystemLog_GprsIdentError	BOOLEAN     	NOT NULL
	,Log_SystemLog_GprsModemNotFound	BOOLEAN     	NOT NULL
	,Log_SystemLog_TimeCorrected	BOOLEAN     	NOT NULL
	,Log_SystemLog_ReportPrinted	BOOLEAN     	NOT NULL
	,Log_SystemLog_RatioDoesntMatch	BOOLEAN     	NOT NULL
	,Log_SystemLog_PollError	BOOLEAN     	NOT NULL
	,Log_SystemLog_MessageSent	BOOLEAN     	NOT NULL
	,Log_SystemLog_UserSessionStarted	BOOLEAN     	NOT NULL
	,Log_SystemLog_AuthenticationError	BOOLEAN     	NOT NULL
	,Log_SystemLog_IncidentClosed	BOOLEAN     	NOT NULL
	,Notification_AdmissionDateNotifyDayCount	INT         	NOT NULL
	,StorageTimeNodeEquipmentHistory	INT         	NOT NULL
	,Poll_DisablePortErrorCount	INT         	NOT NULL
	,Poll_RebootPortErrorCount	INT         	NOT NULL
	,StorageTimeNotifications	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.SystemType;
CREATE TABLE public.SystemType (
	 ID                  	INT         	NOT NULL
	,Title               	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.Task;
CREATE TABLE public.Task (
	 ID                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,FreqType            	INT         	NOT NULL  DEFAULT 4
	,FreqInterval        	INT         	NOT NULL  DEFAULT 1
	,StartTime           	INT         	NOT NULL  DEFAULT 0
	,RetryInterval       	INT         	NOT NULL  DEFAULT 0
	,EndTime             	INT         	NOT NULL  DEFAULT 1439
	,Title               	TEXT        	NOT NULL
	,Enabled             	BOOLEAN     	NOT NULL  DEFAULT true
	,LastRunTime         	TIMESTAMPTZ
	,LastResult          	BOOLEAN
	,LastResultErrorMessage	TEXT        	NOT NULL  DEFAULT ''
	,StartDateTime       	TIMESTAMPTZ 	NOT NULL  DEFAULT current_timestamp
	,Type                	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.Territory;
CREATE TABLE public.Territory (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,ParentId            	INT
	,Name                	TEXT        	NOT NULL
	,TimeZoneOffset      	INT         	NOT NULL
	,OutdoorTempSourceMeasurePointId	INT
);

DROP TABLE IF EXISTS public.TimeZone;
CREATE TABLE public.TimeZone (
	 "offset"            	INT         	NOT NULL
	,Title               	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.Unit;
CREATE TABLE public.Unit (
	 Unit_ID             	INT         	NOT NULL
	,Unit_Title          	TEXT        	NOT NULL
	,Unit_Comment        	TEXT        	NOT NULL
	,Unit_MeasuredParameterID	INT         	NOT NULL
	,Unit_Code           	TEXT        	NOT NULL
	,Unit_BaseUnitID     	INT         	NOT NULL
	,Unit_Multiplier     	REAL        	NOT NULL
);

DROP TABLE IF EXISTS public.UserSessionLog;
CREATE TABLE public.UserSessionLog (
	 Id                  	INT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,AccountId           	INT         	NOT NULL
	,AccountLogin        	TEXT        	NOT NULL
	,AccountDisplayName  	TEXT        	NOT NULL
	,IPAddress           	TEXT        	NOT NULL
	,StartDatetime       	TIMESTAMPTZ 	NOT NULL
	,EndDatetime         	TIMESTAMPTZ
	,ExitCode            	INT         	NOT NULL
	,Application         	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.UserSessionRestoreToken;
CREATE TABLE public.UserSessionRestoreToken (
	 Id                  	BIGINT GENERATED BY DEFAULT AS IDENTITY	NOT NULL
	,AccountId           	INT         	NOT NULL
	,ExpireDate          	TIMESTAMPTZ 	NOT NULL
	,RestoreToken        	TEXT        	NOT NULL
	,CreationDate        	TIMESTAMPTZ 	NOT NULL
	,OriginalIpAddress   	TEXT        	NOT NULL
	,LastActivityDate    	TIMESTAMPTZ 	NOT NULL
	,Application         	TEXT        	NOT NULL
);

DROP TABLE IF EXISTS public.Version;
CREATE TABLE public.Version (
	 Build               	INT         	NOT NULL
	,Version             	TEXT        	NOT NULL
	,Date                	TIMESTAMPTZ 	NOT NULL
	,License             	BYTEA       	NOT NULL
	,LastMigrationBuild  	INT         	NOT NULL
);

DROP TABLE IF EXISTS public.WaterConsumptionCurrent;
CREATE TABLE public.WaterConsumptionCurrent (
	 MeasurePointID      	INT         	NOT NULL
	,DataDate            	TIMESTAMPTZ 	NOT NULL
	,T_in                	REAL
	,T_out               	REAL
	,T_cw                	REAL
	,T_outdoor           	REAL
	,M_in                	REAL
	,M_out               	REAL
	,V_in                	REAL
	,V_out               	REAL
	,H_in                	REAL
	,H_out               	REAL
	,P_in                	REAL
	,P_out               	REAL
	,P_cw                	REAL
	,H_delta             	REAL
	,CalculatedValues    	INT
	,BadValues           	INT
	,V_delta             	REAL
	,M_delta             	REAL
	,T_indoor            	REAL
);

DROP TABLE IF EXISTS public.WaterConsumptionDay;
CREATE TABLE public.WaterConsumptionDay (
	 MeasurePointID      	INT         	NOT NULL
	,DataDate            	TIMESTAMPTZ 	NOT NULL
	,T_in                	REAL
	,M_in                	REAL
	,T_out               	REAL
	,M_out               	REAL
	,H_in                	REAL
	,H_out               	REAL
	,P_in                	REAL
	,P_out               	REAL
	,V_in                	REAL
	,V_out               	REAL
	,NormalOperationDuration	REAL
	,T_cw                	REAL
	,T_outdoor           	REAL
	,H_delta             	REAL
	,Attributes          	INT
	,CalculatedValues    	INT
	,BadValues           	INT
	,InterpolatedValues  	INT
	,StopDuration        	REAL
	,FlowUnderrunDuration	REAL
	,FlowOverrunDuration 	REAL
	,TempDiffLowDuration 	REAL
	,NoPowerDuration     	REAL
	,IncidentDuration    	REAL
	,SaturatedSteamDuration	REAL
	,V_delta             	REAL
	,M_delta             	REAL
	,T_indoor            	REAL
);

DROP TABLE IF EXISTS public.WaterConsumptionHour;
CREATE TABLE public.WaterConsumptionHour (
	 MeasurePointID      	INT         	NOT NULL
	,DataDate            	TIMESTAMPTZ 	NOT NULL
	,T_in                	REAL
	,M_in                	REAL
	,T_out               	REAL
	,M_out               	REAL
	,H_in                	REAL
	,H_out               	REAL
	,P_in                	REAL
	,P_out               	REAL
	,V_in                	REAL
	,V_out               	REAL
	,NormalOperationDuration	REAL
	,T_cw                	REAL
	,T_outdoor           	REAL
	,H_delta             	REAL
	,Attributes          	INT
	,CalculatedValues    	INT
	,BadValues           	INT
	,InterpolatedValues  	INT
	,StopDuration        	REAL
	,FlowUnderrunDuration	REAL
	,FlowOverrunDuration 	REAL
	,TempDiffLowDuration 	REAL
	,NoPowerDuration     	REAL
	,IncidentDuration    	REAL
	,SaturatedSteamDuration	REAL
	,V_delta             	REAL
	,M_delta             	REAL
	,T_indoor            	REAL
);

DROP TABLE IF EXISTS public.WaterConsumptionMonth;
CREATE TABLE public.WaterConsumptionMonth (
	 MeasurePointID      	INT         	NOT NULL
	,DataDate            	TIMESTAMPTZ 	NOT NULL
	,T_in                	REAL
	,M_in                	REAL
	,T_out               	REAL
	,M_out               	REAL
	,H_in                	REAL
	,H_out               	REAL
	,P_in                	REAL
	,P_out               	REAL
	,V_in                	REAL
	,V_out               	REAL
	,NormalOperationDuration	REAL
	,T_cw                	REAL
	,T_outdoor           	REAL
	,H_delta             	REAL
	,Attributes          	INT
	,CalculatedValues    	INT
	,BadValues           	INT
	,InterpolatedValues  	INT
	,StopDuration        	REAL
	,FlowUnderrunDuration	REAL
	,FlowOverrunDuration 	REAL
	,TempDiffLowDuration 	REAL
	,NoPowerDuration     	REAL
	,IncidentDuration    	REAL
	,SaturatedSteamDuration	REAL
	,V_delta             	REAL
	,M_delta             	REAL
	,T_indoor            	REAL
);

DROP TABLE IF EXISTS public.WaterEstimatedConsumption;
CREATE TABLE public.WaterEstimatedConsumption (
	 MeasurePointId      	INT         	NOT NULL
	,PreviousMonth       	BOOLEAN     	NOT NULL
	,StartDate           	TIMESTAMPTZ 	NOT NULL
	,EstimationAlgorithm 	INT         	NOT NULL  DEFAULT 1
	,EndDate             	TIMESTAMPTZ 	NOT NULL
	,M_in                	REAL
	,M_out               	REAL
	,M_delta             	REAL
	,V_in                	REAL
	,V_out               	REAL
	,V_delta             	REAL
	,H_in                	REAL
	,H_out               	REAL
	,H_delta             	REAL
);

DROP TABLE IF EXISTS public.WaterTotals;
CREATE TABLE public.WaterTotals (
	 MeasurePointId      	INT         	NOT NULL
	,DataDate            	TIMESTAMPTZ 	NOT NULL
	,V_in                	REAL
	,V_out               	REAL
	,M_in                	REAL
	,M_out               	REAL
	,H_in                	REAL
	,H_out               	REAL
	,H_delta             	REAL
	,NormalOperationDuration	REAL
	,Flags               	INT         	NOT NULL
	,CalculatedValues    	INT
	,BadValues           	INT
	,ResettedValues      	INT
	,InterpolatedValues  	INT
	,StopDuration        	REAL
	,FlowUnderrunDuration	REAL
	,FlowOverrunDuration 	REAL
	,TempDiffLowDuration 	REAL
	,NoPowerDuration     	REAL
	,IncidentDuration    	REAL
	,SaturatedSteamDuration	REAL
	,V_delta             	REAL
	,M_delta             	REAL
);


-- ROLLBACK;

COMMIT;
